apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: wxsquwf7c-go 
  janus-idp.io/tekton: wxsquwf7c-go
  backstage.io/kubernetes-id: wxsquwf7c-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wxsquwf7c-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml