apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: wxsquwf7c-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:71b649f060e1f7767ffabb8d8d1a1547bbf77468@sha256:ad0e72c8b7b047bed040773d24f66a119e1df27c494c1e2d1141ca363ba7c8ce
          name: container-image
